name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: gemfiles/rails72.gemfile
          - ruby: 3.2
            gemfile: gemfiles/rails71.gemfile
          - ruby: 3.1
            gemfile: gemfiles/rails70.gemfile
          - ruby: 3.3
            gemfile: gemfiles/mongoid9.gemfile
            mongodb: true
          - ruby: 3.1
            gemfile: gemfiles/mongoid8.gemfile
            mongodb: true
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - if: ${{ matrix.mongodb }}
        uses: ankane/setup-mongodb@v1
      - run: sudo apt-get update && sudo apt-get install libsodium23 libvips42 poppler-utils
      - run: bundle exec rake test

      - if : ${{ !matrix.mongodb }}
        uses: ankane/setup-postgres@v1
        with:
          database: lockbox_test
      - if : ${{ !matrix.mongodb }}
        run: ADAPTER=postgresql bundle exec rake test

      - if : ${{ !matrix.mongodb }}
        uses: ankane/setup-mysql@v1
        with:
          database: lockbox_test
      - if : ${{ !matrix.mongodb }}
        run: ADAPTER=mysql2 bundle exec rake test
